FORMAT: 1A
HOST: http://www.google.com

# robert
Robert, User Managment as a Service.

# User


## User [/users]
### List all User [GET]
+ Response 200 (application/json)

        [{
          "id": 1234, "email": "foo@bar"
        }, {
          "id": 2314, "email": "bar@gmail.com"
        }]

### Create a User [POST]
+ Request (application/json)

        { "email": "foo@bar.com" }

+ Parameters
	+ email (required, string, `foo@bar.com`) ... The user email
	+ password (required, string, `secret`) ... The user password in plain text
	
+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
